### ISSUE TITLE
how to get data?

### ISSUE THREAD

**Issue by JLei67** [LinXueyuanStdio/EchoEA#2]

**Comment by LinXueyuanStdio** [comment]
we use the same data as RAGA.
plz refer to RAGA's open source link.

**Comment by LinXueyuanStdio** [comment]
the source code of RAGA is available at https://github.com/zhurboo/RAGA
I kindly cite their dataset:

Datasets
Please download the datasets [here](https://drive.google.com/file/d/1uJ2omzIs0NCtJsGQsyFCBHCXUhoK1mkO/view?usp=sharing) and extract them into root directory.

**Comment by JLei67** [comment]
Thank you very much
